name: Chromatic (staging)
on: push

jobs:
  chromatic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: install
        run: yarn install --frozen-lockfile
      - uses: chromaui/action-canary@latest
        with:
          exitOnceUploaded: true
          onlyChanged: true
          traceChanged: true
          diagnostics: true
        env:
          CHROMATIC_PROJECT_TOKEN: ${{ secrets.STAGING_CHROMATIC_PROJECT_TOKEN }}
          CHROMATIC_INDEX_URL: https://index.staging-chromatic.com
          LOG_LEVEL: debug
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: chromatic-build-artifacts-${{ github.run_id }}
          path: |
            chromatic-diagnostics.json
            **/build-storybook.log
