name: Chromatic Main and Active PRs only
on:
  push:
    branches:
      - main
  pull_request:
    types: [assigned, ready_for_review, review_requested]

permissions:
  contents: read

jobs:
  chromatic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1024
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: actions/setup-node@v3
        with:
          node-version: 22
      - run: corepack enable
      - name: install
        run: yarn install --immutable
      - uses: chromaui/action@latest
        with:
          # 👇 Chromatic projectToken, refer to the manage page to obtain it.
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          exitOnceUploaded: true
          onlyChanged: true
          traceChanged: true
          diagnostics: true
          skip: ${{ github.event.pull_request.draft == true }}
          debug: true
        env:
          NODE_OPTIONS: --max_old_space_size=8192
          CHROMATIC_SHA: ${{ github.event.pull_request.head.sha }}
          CHROMATIC_BRANCH: ${{ github.head_ref }}
          CHROMATIC_SLUG: ${{ github.repository }}
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: chromatic-build-artifacts-${{ github.run_id }}
          path: |
            chromatic-diagnostics.json
            **/build-storybook.log
