name: Test PR

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

permissions:
  contents: read

jobs:
  package-size:
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/package-size.yml
    permissions:
      contents: read
      issues: write
      pull-requests: write
    secrets:
      UPSTASH_REDIS_REST_URL: ${{ secrets.UPSTASH_REDIS_REST_URL }}
      UPSTASH_API_KEY: ${{ secrets.UPSTASH_API_KEY }}
