name: Smoke test via action next
on: merge_group

permissions:
  contents: read

jobs:
  smoke-test-action-next:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: "22.22.3"
      - run: yarn
      - name: Push to action-next
        run: yarn run release-next
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Build and pack the CLI
        run: |
          yarn build
          yarn pack --out chromatic.tgz
      - name: Install fixture deps
        working-directory: smoke-tests
        run: |
          corepack enable
          yarn set version 4.2.2
          yarn install
      - name: Run build against action-next
        uses: chromaui/action-next@latest
        with:
          workingDir: smoke-tests
          buildScriptName: build-storybook
          exitZeroOnChanges: true
          forceRebuild: true
        env:
          LOG_LEVEL: debug
          DEBUG: chromatic-cli
          CHROMATIC_PROJECT_TOKEN: ${{ secrets.SMOKE_TESTS_CHROMATIC_PROJECT_TOKEN }}
